### ISSUE TITLE
"My tickets" doesn't update after submitting a ticket.

### ISSUE THREAD

**Issue by kielgillard** [zendesk/zendesk_sdk_ios#158]
1. Navigate to My Tickets
1. Tap "New"
1. Submit a ticket successfully.

The new ticket modal is dismissed to reveal the "My tickets" modal but the list is empty.

Why isn't it updating out of the box? What should I do to poke it to updating?

**Comment by RonanMcH** [comment]
Hi @kielgillard ,
I have managed to recreate this on iPad only. Have you seen it on iPhone or iPad or both? It is a bug and I have logged it so it should be fixed in the coming releases.  Unfortunately, I cannot give a timeline on when it will be released but we shall update you on it and leave this issue open until it has been fixed and released.
Thanks for bringing it to our attention,
Ronan.

**Comment by kielgillard** [comment]
Thanks! At the moment, we're only building and running our app on iPad only so I only ever see it on iPad.

**Comment by kielgillard** [comment]
Hello team, this is still an issue and it would be great to not have a poor user experience when our users are not in a hugely positive frame of mind when they're submitting a ticket in the first place.

**Comment by oarrabi** [comment]
Hello @kielgillard ,

Sorry for not updating you for long. We prioritized this issue to be fixed and will be delivered in the next release. The next release is expected to be around the end of July.

Thanks :)

**Comment by kielgillard** [comment]
Thanks for the update. Looking forward to the release!

**Comment by RonanMcH** [comment]
Hi @kielgillard ,
This issue has been fixed in our latest release which is now available from the repo.
Thanks for bringing it to our attention,
Ronan.
