### ISSUE TITLE
Help Centre not displayed correctly on iOS 10

### ISSUE THREAD

**Issue by afehners** [zendesk/zendesk_sdk_ios#186]
I'm testing my App on iOS 10 Beta 1

I have noticed  the Help centre is not displayed correctly. I'm pushing it to a navigation controller and the contents are positioned under the top bar. This works correctly on iOS9

`[ZDKHelpCenter pushHelpCenterWithNavigationController:self.navigationController filterByCategoryId:@"my-category-id" categoryName:nil layoutGuide:ZDKLayoutRespectAll];`

All UIViewControllers that I push onto the navigation controller are displayed correctly.

Is there a way to get hold of the UIViewController you're creating so I can push it directly and inspect the object to make any corrections needed?

**Comment by baz8080** [comment]
Hi @afehners 

We've also been looking into the beta. We are planning on waiting for the next seed before testing in earnest, but the SDK will work with iOS 10 when it is released. We don't currently have a way of exposing the UIViewController at the moment.

**Comment by olivaresf** [comment]
Hello! Do you guys have any update on this issue? Still seeing it in Beta 4.

**Comment by mathewcropper** [comment]
Hi there. I just posted an update regarding iOS 10 in our SDK community, ["Chat and Support SDKs: Android 7 (Nougat) and iOS 10 updates"](https://support.zendesk.com/hc/en-us/community/posts/215771787-Support-and-Chat-SDKs-Android-7-Nougat-and-iOS-10-updates).

We have a release planned (hopefully this week) for the Chat SDK to fix issues related to iOS 10. We are currently working on one for the Support SDK.

**Comment by afehners** [comment]
There are also layout issues when displayed in Landscape mode on an iPad running iOS10. It only functions correctly in Portrait orientation, albeit offset incorrectly at the top.

**Comment by RonanMcH** [comment]
Hi @afehners and @olivaresf  ,
We have just released version 1.7.1.1 of the Support SDK. We have fixed all the known issues around iOS 10's latest beta that we could identify. Can you let us know if this has fixed your issues?
Thanks,
Ronan.

**Comment by olivaresf** [comment]
Hi @RonanMcH, this issue is not fixed. I just tried it on Xcode Version 8.0 beta 6 (8S201h). I am trying to `showHelpCenterWithNavController:` and it's presenting correctly. However, the table view is still below the nav bar.

I'm attaching a pic. Let me know if I can help.
<img width="432" alt="screen shot 2016-08-18 at 11 54 42 am" src="https://cloud.githubusercontent.com/assets/253485/17782735/9980ca5c-653a-11e6-9b3e-051baca5fd3e.png">

**Comment by RonanMcH** [comment]
Hi @olivaresf ,
I am struggling to recreate this bug of the table view being below the navigation bar.  The method `showHelpCenterWithNavController:` does not exist in version 1.7.1.1 of the Support SDK. I have tried `showHelpCenterWithNavController:` which works correctly and  `presentHelpCenterWithViewController:` which works perfectly. Are you sure you have updated to the latest release?
Thanks,
Ronan.

**Comment by afehners** [comment]
All fixed for me on both iPhone and iPad iOS10

**Comment by tecknut** [comment]
@afehners I'm going to close this issue as you've stated it's been solved. @olivaresf feel free to re-open this issue if you're still experiencing this problem.
