### ISSUE TITLE
Integer literal 'xxxxxxxxxxxx' overflows when stored into 'Int'

### ISSUE THREAD

**Issue by sheff1422** [zendesk/zendesk_sdk_ios#371]
- SDK version: 2.0
- Xcode version: 9.3
- iOS or Simulator: Simulator
- iOS Version: 11.3
- Swift version: 4.0

Steps to Reproduce:

1. Try to set such config and compile
let hcConfig = HelpCenterUiConfiguration()
        hcConfig.groupType = .section
        hcConfig.groupIds = [123456789012]

**Comment by RonanMcH** [comment]
Hi @sheff1422 , 
We just published Support SDK version 2.0.2 with a fix for this issue.
Thanks,
Ronan.

**Comment by sheff1422** [comment]
@RonanMcH Updated to 2.02 and the issue is still there while archiving.

**Comment by divo** [comment]
@sheff1422 Can you try passing `123456789012` as an `NSNumber` and not an `Int`?
